### ISSUE TITLE
Multiple Images in Full Preview & Caption

### ISSUE THREAD

**Issue by potateaux** [kamilczujowski/least#7]
hey, thanks for creating this gallery! i've been looking everywhere for something like this

i have two questions, i hope you don't mind me asking
1. is it possible to add multiple images inside the full preview? if so, how can it be done? 
2. i want to customize the caption inside the full preview, such as making a certain word a bigger size than the rest of the text. how can i do that without it messing up the gallery altogether? i tried playing around with it and the layout ends up getting messed up from it

any help is appreciated, thank you

**Comment by angiemck39** [comment]
Hi, this is a fantastic image gallery and pretty much what I was looking for but I too have the same question as "potateaux":
1. Is it possible to add multiple images inside the full preview? and if so, how can it be done? Or can you provide a small snippet of code if it is easy to do. ( I am more of a designer and can edit html and css though I'm not sure how to do this.)

Any help or advice would be greatly appreciated or if its not possible at this time would something like this be incorporated at some stage in the near future?  

many thanks in advance
Angela

**Comment by kamilczujowski** [comment]
Hey!

Thanks for your feedback!

@potateaux & @angiemck39 
1. Not now - We are working on this feature for the next least.js version (2.0 coming next year)!
You can add two images into 1 - like this: http://autoserviceressel.de/img/aboutus.jpg

@potateaux
2. You can edit all the default styles in "least.scss"

**Comment by potateaux** [comment]
@kamilczujowski thanks for the response, looking forward to the next version!

i have another question: i want each full preview to have a title above the "fullPreview" image (after it slides out). how can this be done? i've tried making a separate class for the title but i think i have to edit something with the js script in order for it to appear. but i'm new with jquery so i don't know how to solve this

thanks again

**Comment by angiemck39** [comment]
@kamilczujowski Im sorry for the late reply, thankyou for responding above and for the private message, its much appreciated. 

cheers

**Comment by kamilczujowski** [comment]
@angiemck39 no problem! :)

@potateaux which title do you mean? under the (big) full preview?

**Comment by potateaux** [comment]
@kamilczujowski yes the (big) full preview

**Comment by kamilczujowski** [comment]
@potateaux.
You can use a div with class for description (< div class=" projectInfo " >...) for your full preview title.
Just edit following CSS-Class "section #fullPreview .fullCaption" and add following styles: position: absolute; top: 0; left: 0; right: 0;

section #fullPreview .fullCaption {
font-family: Helvetica, Arial, sans-serif;
font-size: 13px;
line-height: 15px;
font-weight: 300;
color: white;
margin: 15px auto 0 auto;
position: absolute;
top: 0;
left: 0;
right: 0;

are you looking for something like this? :)
![bildschirmfoto 2014-01-07 um 11 54 43](https://f.cloud.github.com/assets/4048433/1858329/2261a536-778a-11e3-9660-6402e6302cb2.png)

**Comment by potateaux** [comment]
@kamilczujowski wow thanks! i feel like an idiot, it's such an easy solution haha
