### ISSUE TITLE
smaller fullView

### ISSUE THREAD

**Issue by DavidDefossez** [kamilczujowski/least#9]
Hi, I have a question about the fullPreview,
When I press a thumbnail to show the bigger picture, I want it to be shown in 480 x 480 instead of the standard 960 x 600. Is this possible ?

I have tried to size it to 480 x 480 but it will automaticly stretch to 960 x 600..

**Comment by kamilczujowski** [comment]
Hey @DavidDefossez!

Again - sorry for my late answer.

You can only change the "width"-size of "preview-image"
First: you need to use "least.js 2" - https://github.com/kamilczujowski/least.js-2

After that you need to edit the "_option.scss" (src/scss/assets/_options.scss) and the following style:

/\* @group Gallery-Fullscreen _/
$max-fullscreen-size: 960px; /_ default size for fullscreen preview _/
/_ @end */

just change 960px with 480px;

i hope i could help you :-)

**Comment by DavidDefossez** [comment]
not a problem at all !
Thank you for the info, I'll give it a go today and keep you posted :-)

**UPDATE***

It worked ! thank you again :-) :+1:
